[package]
name = "haloswap"
version = "0.1.0"
authors = ["Aura network"]
edition = "2021"
description = "Common halo types"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
# for quicker tests, cargo test --lib
# for more explicit tests, cargo test --features=backtraces
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-schema = "1.1.8"
cw20 = { version = "1.0.0" } 
cosmwasm-storage = { version = "1.1.8" }
cosmwasm-std = { version = "1.1.8", features = ["stargate"] }
schemars = "0.8.11"

[dev-dependencies]
cosmwasm-schema = { version = "1.1.8" }

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
