[package]
name = "bignumber"
version = "0.1.0"
authors = ["Aura network"]
edition = "2021"
description = "Bignumber library for cosmwasm project"
license = "Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
backtraces = ["cosmwasm-std/backtraces"]

[dependencies]
cosmwasm-std = { version = "1.1.8", features = ["stargate"] }
bigint = "4.4.3"
schemars = "0.8.11"
serde = { version = "1.0.148", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = "1.1.8"
